package com.github.tubicz.coupon_service.adapter.in.web.exception;

enum ErrorCode {
    INCORRECT_REQUEST_BODY,
    CONSTRAINT_VIOLATION,
    INVALID_COUPON_CODE_FORMAT,
    INVALID_COUPON_USAGE_LIMIT,
    COUPON_ALREADY_EXISTS,
    COUPON_NOT_FOUND,
    COUPON_EXHAUSTED,
    COUPON_ALREADY_REDEEMED,
    COUPON_NOT_ELIGIBLE_FOR_COUNTRY,
    IP_NOT_RESOLVABLE,
    COUNTRY_NOT_FOUND,
}
